# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/_images` folder and
# use grunt task `build` to synchronize assets

# Image directory (default: images)
image_dir: assets/images

# Sidebar Configuration
#    You can add groups of links and links much as you want
#    You just have to respect the indentation : `groups of links` -> `link` -> `title, link, icon`
#    Example :
#    -------------
#       sidebar:                   # DON'T modify this variable name
#            menu:                 # Name of your groups of links (changeable)
#                home:             # Name of your link (changeable)
#                   title: Home    # Title of your link displayed
#                   url: /         # URL of the link. If the URL is internal, domain name is not necessary
#                   icon: home     # Name of the font awesome icon class without the `fa-`
#                                  # Go to http://fontawesome.io/icons/ to find class name of icon
sidebar:
    menu:
        home:
            title: sidebar.menu.home.title
            url: sidebar.menu.home.url
            icon: home
        categories:
            title: sidebar.menu.categories.title
            url: sidebar.menu.categories.url
            icon: bookmark
        tags:
            title: sidebar.menu.tags.title
            url: sidebar.menu.tags.url
            icon: tags
        archives:
            title: sidebar.menu.archives.title
            url: sidebar.menu.archives.url
            icon: archive
        search:
            title: sidebar.menu.search.title
            url: sidebar.menu.search.url
            icon: search
            # `st-search-show-outputs` classes are used to open swiftype search window
            class: st-search-show-outputs
        about:
            title: sidebar.menu.about.title
            url: sidebar.menu.about.url
            icon: question
    author_links:
         github:
             title: sidebar.author_links.github.title
             url: sidebar.author_links.github.url
             icon: github
         stack_overflow:
             title: sidebar.author_links.stack_overflow.title
             url: sidebar.author_links.stack_overflow.url
             icon: stack-overflow
        # twitter:
        #     title: Twitter
        #     url: https://twitter.com/
        #     icon: twitter
        # facebook:
        #     title: Facebook
        #     url: https://www.facebook.com/
        #     icon: facebook
        # google_plus:
        #     title: Google +
        #     url: https://plus.google.com/
        #     icon: google-plus
         linked_in:
             title: sidebar.author_links.linked_in.title
             url: sidebar.author_links.linked_in.url
             icon: linkedin
        # mail:
        #     title: Mail
        #     url: mailto:
        #     icon: envelope-o
         shelfari:
             title: sidebar.author_links.shelfari.title
             url: sidebar.author_links.shelfari.url
             icon: book
    rss:
        rss:
            title: sidebar.rss.rss.title
            url: sidebar.rss.rss.url
            icon: rss

# Header configuration
# The link at the right of the header is customizable
# You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
# DON'T edit `header`, `right_link`, `url`, `icon` and `class` variable name
header:
    right_link:
         # url: /#search
         # icon: search
         # class: st-search-show-outputs

# Author
author:
    email: author.email 
    bio: author.bio
    job: author.job
    location: author.location
    # Your profile picture located in folder `source/_images/` (development)
    # or in `source/assets/images/` (production).
    # Overwritten by your gravatar image if `gravatar_image` is enabled
    picture:
    #profile.jpg

# Customization
# Define the behavior of the sidebar
# 1: Display large sidebar on large screen, medium sidebar on medium screen and header bar on small screen
# and large sidebar is swiped (default)
# 2: Display medium sidebar on large and medium screen and header bar on small screen and medium sidebar is swiped
# 3: Display header bar on all screens and large sidebar is swiped
# 4: Display header bar on all screens and medium sidebar is swiped
sidebar_behavior: 1
# Display thumbnail image of each post on index pages (disable: 0, enable: 1)
thumbnail_image: 1
# Message displayed after the <!-- more --> tag
read_more_message: read_more_message
# Message displayed after the <!-- more --> tag or after 300 characters for post with link layout
go_to_message: go_to_message
# Your blog cover picture located in folder `source/_images/` (development) or in `source/assets/images/` (production)
cover_image: cover.png
# Your favicon located in folder `source/_images/` (development) or in `source/assets/images/` (production)
favicon:
# Display an image gallery at the end of a post which have photos variables
image_gallery: 1
# Pagination behavior of archive, category and tag pages
## 0: Disable pagination
## 1: Enable pagination
archive_pagination: 1
category_pagination: 1
tag_pagination: 1

# Integrated services
# Your Disqus shortname
disqus_shortname: marlonpatrickdicasdeumprogramador
# Your Google analystics web property ID : UA-XXXXX-X
google_analytics_id: UA-29896969-1
# Your Gravatar email. Overwrite `author.picture` everywhere in the blog
gravatar_email: 
# Your swiftype install key
swiftype_install_key: PfLcPuxspuRJ_JEy-A8a 

